CREATE TABLE TASKS (ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100),
DESCRIPTION VARCHAR(250),
START_DATE DATE,
END_DATE DATE,
STATUS INT);

CREATE TABLE ELEMENT_OF_TASK (ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
FOREIGN KEY(TASK_ID) REFERENCES TASKS(ID),
NAME_OF_ELEMENT VARCHAR(100),
DESCRIPTION varchar(250),
TASK_ID INT,
VALUE VARCHAR(100));